/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan
         * @description Scan one artifact submission and return a ``ScanReport`` (JSON or SARIF).
         */
        post: operations["scan_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactKind
         * @description The three artifact kinds v1 recognizes, each with its own analysis profile.
         * @enum {string}
         */
        ArtifactKind: "skill" | "agents" | "claude_md";
        /** ArtifactMeta */
        ArtifactMeta: {
            kind: components["schemas"]["ArtifactKind"];
            /** Name */
            name?: string | null;
            /** Scope */
            scope?: string | null;
        };
        /** Body_scan_scan_post */
        Body_scan_scan_post: {
            /**
             * Content
             * @description Artifact body (mode=text).
             */
            content?: string | null;
            /**
             * File
             * @description Uploaded .zip bundle (mode=zip).
             */
            file?: string | null;
            /**
             * Filename
             * @description Declared filename for pasted text or a zip.
             */
            filename?: string | null;
            /** @description Artifact-kind hint for pasted text. */
            kind_hint?: components["schemas"]["KindHint"] | null;
            /** @description Which input channel this submission uses. */
            mode: components["schemas"]["ScanMode"];
            /**
             * Url
             * @description Remote git URL (mode=git).
             */
            url?: string | null;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "prompt_injection" | "command_execution" | "data_exfiltration" | "excessive_agency" | "secret_exposure" | "supply_chain" | "context_poisoning" | "obfuscation" | "trigger_abuse" | "tool_poisoning" | "manifest_validation";
        /** Component */
        Component: {
            /**
             * Executable
             * @default false
             */
            executable: boolean;
            /** Language */
            language?: string | null;
            /** Path */
            path: string;
            type: components["schemas"]["ComponentType"];
        };
        /**
         * ComponentType
         * @enum {string}
         */
        ComponentType: "manifest" | "script" | "reference" | "asset" | "other";
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "high" | "medium" | "low";
        /** Finding */
        Finding: {
            category: components["schemas"]["Category"];
            confidence: components["schemas"]["Confidence"];
            /** Evidence */
            evidence: string;
            /** Id */
            id: string;
            /** Language */
            language?: string | null;
            location: components["schemas"]["Location"];
            /** Raised By */
            raised_by?: string | null;
            /** Remediation */
            remediation: string;
            /** Risk */
            risk: string;
            severity: components["schemas"]["Severity"];
            source_layer: components["schemas"]["SourceLayer"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportKind
         * @description Classification of a CLAUDE.md ``@import`` target.
         * @enum {string}
         */
        ImportKind: "in_tree" | "out_of_tree" | "remote";
        /** ImportRef */
        ImportRef: {
            kind: components["schemas"]["ImportKind"];
            /** Raw */
            raw: string;
            /**
             * Resolved
             * @default false
             */
            resolved: boolean;
            /** Target */
            target: string;
        };
        /**
         * KindHint
         * @description Optional artifact-kind hint for pasted text (picks the default filename).
         * @enum {string}
         */
        KindHint: "skill" | "agents" | "claude_md";
        /** Location */
        Location: {
            /** File */
            file: string;
            /** Line */
            line?: number | null;
        };
        /**
         * ScanMode
         * @description Which of the three input channels a submission uses (exactly one per request).
         * @enum {string}
         */
        ScanMode: "text" | "zip" | "git";
        /** ScanReport */
        ScanReport: {
            artifact_meta: components["schemas"]["ArtifactMeta"];
            /** Components */
            components?: components["schemas"]["Component"][];
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /** Imports */
            imports?: components["schemas"]["ImportRef"][];
            /** Judges Used */
            judges_used?: string[];
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** @default CLEAN */
            verdict: components["schemas"]["Verdict"];
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low" | "info";
        /**
         * SourceLayer
         * @enum {string}
         */
        SourceLayer: "static_rules" | "manifest" | "ast_python" | "ast_shell" | "taint" | "obfuscation" | "supply_chain" | "judge";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "CLEAN" | "CAUTION" | "DO_NOT_INSTALL";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    scan_scan_post: {
        parameters: {
            query?: {
                /** @description Set to 'sarif' for SARIF 2.1.0. */
                format?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_scan_scan_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
